document.addEventListener("DOMContentLoaded",()=>{
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
 const loader=$("#pageLoader"); setTimeout(()=>loader?.remove(),1400);
 const year=$("#year"); if(year) year.textContent=new Date().getFullYear();
 const translations={
  pl:{nav_start:"START",nav_offer:"OFERTA",nav_about:"O NAS",nav_video:"VIDEO",nav_menu:"MENU",nav_reserve:"REZERWACJA",nav_reviews:"RECENZJE",nav_gallery:"GALERIA",hero_eyebrow:"WARSZAWA • WŁOCHY",hero_title:"Smak,<br><em>który łączy.</em>",hero_text:"Kuchnia fusion, świeże składniki i wyjątkowa atmosfera przy Popularnej 71.",hero_menu:"ZOBACZ MENU",hero_today:"ZOBACZ, CO OFERUJEMY DZISIAJ",hero_scroll:"PRZEWIŃ ↓",about_label:"02 / O NAS",about_eyebrow:"MONTOWNIA SMAKÓW",about_title:"Więcej niż<br><em>restauracja.</em>",about_p1:"Montownia Smaków to klimatyczne miejsce na warszawskiej Woli, gdzie nowoczesne wnętrze spotyka się z kuchnią pełną różnych smaków.",about_p2:"W karcie znajdziesz m.in. burgery, pasty, ramen, curry, żeberka, sałatki, desery i sezonowe propozycje.",about_gallery:"ZOBACZ GALERIĘ",quote_author:"GEORGE BERNARD SHAW",video_section_label:"03 / VIDEO",video_title:"Smak zaczyna się<br><em>w kuchni.</em>",video_note:"MONTOWNIA SMAKÓW · VIDEO",menu_label:"04 / MENU",menu_title:"Nasze <em>menu.</em>",menu_intro:"Przeglądaj kartę strona po stronie.",full_menu:"PEŁNE MENU ↗",reviews_label:"05 / RECENZJE",reviews_title:"Goście <em>mówią.</em>",google:"GOOGLE",more_reviews:"ZOBACZ WIĘCEJ OPINII ↗",gallery_label:"06 / GALERIA",gallery_title:"Montownia<br><em>w obiektywie.</em>",photos:"12 ZDJĘĆ",contact_label:"07 / KONTAKT",contact_title:"Widzimy się<br><em>na Popularnej.</em>",hours:"GODZINY OTWARCIA",map:"OTWÓRZ MAPĘ ↗",shortcuts:"NA SKRÓTY",contact:"KONTAKT",follow:"ŚLEDŹ NAS",presentation:"STRONA PREZENTACYJNA",footer_desc:"Tworzymy, komponujemy, montujemy… smaki!",reservation:"REZERWACJA",call:"ZADZWOŃ",catering:"CATERING"},
  en:{nav_start:"HOME",nav_offer:"OFFER",nav_about:"ABOUT",nav_video:"VIDEO",nav_menu:"MENU",nav_reserve:"RESERVATION",nav_reviews:"REVIEWS",nav_gallery:"GALLERY",hero_eyebrow:"WARSAW • WŁOCHY",hero_title:"A taste<br><em>that brings us together.</em>",hero_text:"Fusion cuisine, fresh ingredients and a unique atmosphere at Popularna 71.",hero_menu:"VIEW MENU",hero_today:"SEE WHAT WE OFFER TODAY",hero_scroll:"SCROLL ↓",about_label:"02 / ABOUT",about_eyebrow:"MONTOWNIA SMAKÓW",about_title:"More than a<br><em>restaurant.</em>",about_p1:"Montownia Smaków is a welcoming place in Warsaw where a modern interior meets a kitchen full of different flavours.",about_p2:"The menu includes burgers, pasta, ramen, curry, ribs, salads, desserts and seasonal specials.",about_gallery:"VIEW GALLERY",quote_author:"GEORGE BERNARD SHAW",video_section_label:"03 / VIDEO",video_title:"Taste begins<br><em>in the kitchen.</em>",video_note:"MONTOWNIA SMAKÓW · VIDEO",menu_label:"04 / MENU",menu_title:"Our <em>menu.</em>",menu_intro:"Browse the menu page by page.",full_menu:"FULL MENU ↗",reviews_label:"05 / REVIEWS",reviews_title:"Guests <em>speak.</em>",google:"GOOGLE",more_reviews:"SEE MORE REVIEWS ↗",gallery_label:"06 / GALLERY",gallery_title:"Montownia<br><em>through the lens.</em>",photos:"12 PHOTOS",contact_label:"07 / CONTACT",contact_title:"See you<br><em>at Popularna.</em>",hours:"OPENING HOURS",map:"OPEN MAP ↗",shortcuts:"SHORTCUTS",contact:"CONTACT",follow:"FOLLOW US",presentation:"PRESENTATION WEBSITE",footer_desc:"We create, compose and assemble… flavours!",reservation:"RESERVATION",call:"CALL US",catering:"CATERING"},
  uk:{nav_start:"ГОЛОВНА",nav_offer:"ПРОПОЗИЦІЯ",nav_about:"ПРО НАС",nav_video:"ВІДЕО",nav_menu:"МЕНЮ",nav_reserve:"БРОНЮВАННЯ",nav_reviews:"ВІДГУКИ",nav_gallery:"ГАЛЕРЕЯ",hero_eyebrow:"ВАРШАВА • ВЛОХИ",hero_title:"Смак,<br><em>що об'єднує.</em>",hero_text:"Ф'южн-кухня, свіжі інгредієнти та особлива атмосфера на Popularna 71.",hero_menu:"ПЕРЕГЛЯНУТИ МЕНЮ",hero_today:"ДИВИТИСЯ, ЩО ПРОПОНУЄМО СЬОГОДНІ",hero_scroll:"ГОРТАЙТЕ ↓",about_label:"02 / ПРО НАС",about_eyebrow:"MONTOWNIA SMAKÓW",about_title:"Більше ніж<br><em>ресторан.</em>",about_p1:"Montownia Smaków — атмосферне місце у Варшаві, де сучасний інтер'єр поєднується з кухнею, сповненою різноманітних смаків.",about_p2:"У меню ви знайдете бургери, пасту, рамен, карі, реберця, салати, десерти та сезонні страви.",about_gallery:"ПЕРЕГЛЯНУТИ ГАЛЕРЕЮ",quote_author:"ДЖОРДЖ БЕРНАРД ШОУ",video_section_label:"03 / ВІДЕО",video_title:"Смак починається<br><em>на кухні.</em>",video_note:"MONTOWNIA SMAKÓW · ВІДЕО",menu_label:"04 / МЕНЮ",menu_title:"Наше <em>меню.</em>",menu_intro:"Переглядайте меню сторінка за сторінкою.",full_menu:"ПОВНЕ МЕНЮ ↗",reviews_label:"05 / ВІДГУКИ",reviews_title:"Гості <em>кажуть.</em>",google:"GOOGLE",more_reviews:"БІЛЬШЕ ВІДГУКІВ ↗",gallery_label:"06 / ГАЛЕРЕЯ",gallery_title:"Montownia<br><em>в об'єктиві.</em>",photos:"12 ФОТО",contact_label:"07 / КОНТАКТ",contact_title:"Зустрінемось<br><em>на Popularna.</em>",hours:"ГОДИНИ РОБОТИ",map:"ВІДКРИТИ МАПУ ↗",shortcuts:"ШВИДКІ ПОСИЛАННЯ",contact:"КОНТАКТ",follow:"СЛІДКУЙТЕ ЗА НАМИ",presentation:"ПРЕЗЕНТАЦІЙНИЙ САЙТ",footer_desc:"Створюємо, поєднуємо, монтуємо… смаки!",reservation:"БРОНЮВАННЯ",call:"ЗАТЕЛЕФОНУВАТИ",catering:"КЕЙТЕРИНГ"}
 };
 const langButtons=$$(".lang-btn");
 function applyLanguage(lang){const t=translations[lang]||translations.pl;document.documentElement.lang=lang==="uk"?"uk":lang;document.body.dataset.lang=lang;$$('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(t[k]!==undefined)el.innerHTML=t[k]});langButtons.forEach(b=>{const a=b.dataset.lang===lang;b.classList.toggle("bg-white",a);b.classList.toggle("text-[#111]",a);b.classList.toggle("bg-transparent",!a);b.classList.toggle("text-white/60",!a)});localStorage.setItem("montownia-language",lang)}
 langButtons.forEach(b=>b.addEventListener("click",()=>applyLanguage(b.dataset.lang)));
 const header=$("#siteHeader"); window.addEventListener("scroll",()=>{if(window.scrollY>25){header.classList.add("bg-blackfood/95","backdrop-blur-xl","h-[68px]");header.classList.remove("h-[82px]")}else{header.classList.remove("bg-blackfood/95","backdrop-blur-xl","h-[68px]");header.classList.add("h-[82px]")}},{passive:true});
 const mobile=$("#mobileMenu"),nav=$("#mainNav"); mobile?.classList.remove("hidden");
 mobile?.addEventListener("click",()=>{const open=nav.dataset.open!=="true";nav.dataset.open=String(open);nav.classList.toggle("hidden",!open);nav.classList.toggle("flex",open);nav.classList.toggle("w-[calc(100vw-36px)]",open);nav.classList.toggle("flex-col",open);nav.classList.toggle("items-start",open);nav.classList.toggle("gap-0",open);nav.classList.toggle("rounded-b-xl",open);nav.classList.toggle("bg-blackfood/95",open);nav.classList.toggle("p-6",open);nav.classList.toggle("shadow-2xl",open);mobile.setAttribute("aria-expanded",String(open));});
 $$("#mainNav a").forEach(a=>a.addEventListener("click",()=>{nav.dataset.open="false";if(innerWidth<768)nav.classList.add("hidden")}));
 $$('a[href^="#"]').forEach(a=>a.addEventListener("click",e=>{const t=document.querySelector(a.getAttribute("href"));if(!t)return;e.preventDefault();t.scrollIntoView({behavior:"smooth",block:"start"})}));
 const video=$("#siteVideo");if(video){const start=27,startVideo=()=>{try{if(Number.isFinite(video.duration)&&video.duration>start+1&&video.currentTime<1)video.currentTime=start;video.play()?.catch(()=>{})}catch{}};video.addEventListener("loadeddata",startVideo);video.addEventListener("canplay",startVideo,{once:true});video.addEventListener("ended",()=>{try{video.currentTime=start;startVideo()}catch{}});video.addEventListener("click",()=>video.paused&&startVideo())}
 const pages=[{src:"https://montowniasmakow.pl/wp-content/uploads/2025/07/0001-1024x746.png",alt:"Menu Montownia Smaków — strona 1"},{src:"https://montowniasmakow.pl/wp-content/uploads/2025/07/0002-1024x746.png",alt:"Menu Montownia Smaków — strona 2"},{src:"https://montowniasmakow.pl/wp-content/uploads/2024/12/drink-menu-2.pdf-967x1024.png",alt:"Menu napojów Montownia Smaków"},{src:"https://montowniasmakow.pl/wp-content/uploads/2024/12/drink-menu-2.pdf1_-967x1024.png",alt:"Menu win i piwa Montownia Smaków"}];let mi=0;const img=$("#menuPage"),counter=$("#menuCounter"),dots=$("#menuDots");pages.forEach((p,i)=>{const d=document.createElement("button");d.type="button";d.dataset.index=i;d.className="menu-dot h-11 w-11 rounded-full border border-[#777] bg-transparent";d.addEventListener("click",()=>showMenu(i));dots?.appendChild(d)});function showMenu(i){mi=(i+pages.length)%pages.length;if(img){img.src=pages[mi].src;img.alt=pages[mi].alt}if(counter)counter.textContent=`0${mi+1} / 04`;$$('.menu-dot').forEach((d,n)=>{d.classList.toggle("bg-white",n===mi);d.classList.toggle("bg-transparent",n!==mi)})}$("#menuPrev")?.addEventListener("click",()=>showMenu(mi-1));$("#menuNext")?.addEventListener("click",()=>showMenu(mi+1));showMenu(0);
 const sources=$$("#galleryGrid img").map(i=>i.src),modal=$("#galleryModal"),modalImg=$("#galleryModalImage"),gc=$("#galleryCounter");let gi=0;function showGallery(i){gi=(i+sources.length)%sources.length;if(modalImg)modalImg.src=sources[gi];if(gc)gc.textContent=`${String(gi+1).padStart(2,"0")} / ${String(sources.length).padStart(2,"0")}`}function openGallery(i=0){showGallery(i);modal.classList.remove("hidden","pointer-events-none","opacity-0");modal.classList.add("flex","pointer-events-auto","opacity-100");document.body.classList.add("overflow-hidden");modal.setAttribute("aria-hidden","false")}function closeGallery(){modal.classList.add("hidden","pointer-events-none","opacity-0");modal.classList.remove("flex","pointer-events-auto","opacity-100");document.body.classList.remove("overflow-hidden");modal.setAttribute("aria-hidden","true")}$$('.gallery-card').forEach(c=>c.addEventListener("click",()=>openGallery(Number(c.dataset.index))));$("#galleryPrev")?.addEventListener("click",()=>showGallery(gi-1));$("#galleryNext")?.addEventListener("click",()=>showGallery(gi+1));$("#galleryClose")?.addEventListener("click",closeGallery);modal?.addEventListener("click",e=>e.target===modal&&closeGallery());document.addEventListener("keydown",e=>{if(modal?.classList.contains("hidden"))return;if(e.key==="Escape")closeGallery();if(e.key==="ArrowRight")showGallery(gi+1);if(e.key==="ArrowLeft")showGallery(gi-1)});
 applyLanguage(localStorage.getItem("montownia-language")||"pl");
});
